import { NextRequest, NextResponse } from 'next/server';
import { prisma, isPrismaConstraintError, prismaConstraintMessage } from '@/lib/prisma';
import { generateAccessCode, hashAccessCode } from '@/lib/auth';
import { guardApi } from '@/lib/api-auth';
import dataStore from '@/lib/data-store';

/**
 * Generates (or rotates) a depot user's access code. The plaintext code is
 * returned exactly once in this response — only its hash is ever persisted,
 * so it cannot be recovered afterward and must be regenerated if lost.
 */
export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const auth = await guardApi(req, 'users.write');
  if (!auth.ok) return auth.response;

  try {
    let target: any = await prisma.user.findUnique({ where: { id } }).catch(() => null);
    if (!target) {
      target = dataStore.getUserById(id);
    }
    if (!target) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 });
    }

    if (target.role !== 'DEPOT_USER') {
      return NextResponse.json(
        { error: 'Access codes are only issued to Depot users.' },
        { status: 400 }
      );
    }

    // Regenerate on collision (astronomically unlikely with an 8-char code
    // from a 33-symbol alphabet, but the unique index makes it cheap to guard).
    let code = generateAccessCode();
    let { accessCodeHash, accessCodeLookupHash } = hashAccessCode(code);

    try {
      await prisma.user.update({
        where: { id },
        data: { accessCodeHash, accessCodeLookupHash },
      });
    } catch (dbErr) {
      if (isPrismaConstraintError(dbErr) && (dbErr as any).code === 'P2002') {
        code = generateAccessCode();
        ({ accessCodeHash, accessCodeLookupHash } = hashAccessCode(code));
        try {
          await prisma.user.update({ where: { id }, data: { accessCodeHash, accessCodeLookupHash } });
        } catch {}
      }
    }

    dataStore.updateUser(id, { accessCodeHash, accessCodeLookupHash });

    dataStore.addAuditLog({
      action: 'USER_PERMISSION_CHANGE',
      entityType: 'USER',
      entityId: target.id,
      entityLabel: `${target.name} (${target.role})`,
      description: `Depot access code regenerated by ${auth.user?.name || 'Admin'}`,
    });

    return NextResponse.json({
      success: true,
      accessCode: code,
      message: `New access code generated for ${target.name}. Share it securely — it will not be shown again.`,
    });
  } catch (error: any) {
    console.error('Access code generation error:', error);
    return NextResponse.json({ error: error.message || 'Failed to generate access code' }, { status: 500 });
  }
}
